require 'helper'

class Reline::KeyActor::Emacs::Test < Test::Unit::TestCase
  def setup
    @prompt = '> '
    @line_editor = Reline::LineEditor.new(Reline::KeyActor::Emacs, @prompt)
  end

  def input_keys(input)
    input.chars.each do |c|
      if c.bytesize == 1
        eighth_bit = 0b10000000
        byte = c.bytes.first
        if byte.allbits?(eighth_bit)
          @line_editor.input_key("\e".ord)
          byte ^= eighth_bit
        end
        @line_editor.input_key(byte)
      else
        c.bytes.each do |byte|
          @line_editor.input_key(byte)
        end
      end
    end
  end

  def test_ed_insert_one
    input_keys('a')
    assert_equal('a', @line_editor.line)
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_insert_two
    input_keys('ab')
    assert_equal('ab', @line_editor.line)
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_insert_mbchar_one
    input_keys('か')
    assert_equal('か', @line_editor.line)
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_insert_mbchar_two
    input_keys('かき')
    assert_equal('かき', @line_editor.line)
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_insert_for_mbchar_by_plural_code_points
    input_keys("か\u3099")
    assert_equal("か\u3099", @line_editor.line)
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_insert_for_plural_mbchar_by_plural_code_points
    input_keys("か\u3099き\u3099")
    assert_equal("か\u3099き\u3099", @line_editor.line)
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_move_next_and_prev
    input_keys('abd')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('c')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abcd', @line_editor.line)
  end

  def test_move_next_and_prev_for_mbchar
    input_keys('かきけ')
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('く')
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('かきくけ', @line_editor.line)
  end

  def test_move_next_and_prev_for_mbchar_by_plural_code_points
    input_keys("か\u3099き\u3099け\u3099")
    assert_equal(18, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("く\u3099")
    assert_equal(18, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("か\u3099き\u3099く\u3099け\u3099", @line_editor.line)
  end

  def test_move_to_beg_end
    input_keys('bcd')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('a')
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-e")
    assert_equal(4, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('e')
    assert_equal(5, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(5, @line_editor.instance_variable_get(:@cursor))
    assert_equal(5, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abcde', @line_editor.line)
  end

  def test_newline
    input_keys('ab')
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    refute(@line_editor.finished?)
    input_keys("\C-m")
    assert_equal("ab\n", @line_editor.line)
    assert(@line_editor.finished?)
  end

  def test_delete_prev_char
    input_keys('ab')
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-h")
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('a', @line_editor.line)
  end

  def test_delete_prev_char_for_mbchar
    input_keys('かき')
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-h")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('か', @line_editor.line)
  end

  def test_delete_prev_char_for_mbchar_by_plural_code_points
    input_keys("か\u3099き\u3099")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-h")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("か\u3099", @line_editor.line)
  end

  def test_ed_kill_line
    input_keys("\C-k")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
    input_keys('abc')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-k")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abc', @line_editor.line)
    input_keys("\C-b\C-k")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('ab', @line_editor.line)
  end

  def test_em_kill_line
    input_keys("\C-u")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
    input_keys('abc')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-u")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
    input_keys("abc\C-b\C-u")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('c', @line_editor.line)
    input_keys("\C-u")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('c', @line_editor.line)
  end

  def test_ed_move_to_beg
    input_keys('abd')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('c')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('012')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('012abcd', @line_editor.line)
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('ABC')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('ABC012abcd', @line_editor.line)
    input_keys("\C-f" * 10 + "\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('a')
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(11, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('aABC012abcd', @line_editor.line)
  end

  def test_ed_move_to_end
    input_keys('abd')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('c')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-e")
    assert_equal(4, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('012')
    assert_equal(7, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abcd012', @line_editor.line)
    input_keys("\C-e")
    assert_equal(7, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('ABC')
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abcd012ABC', @line_editor.line)
    input_keys("\C-b" * 10 + "\C-e")
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@cursor_max))
    input_keys('a')
    assert_equal(11, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(11, @line_editor.instance_variable_get(:@cursor))
    assert_equal(11, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abcd012ABCa', @line_editor.line)
  end

  def test_em_delete_or_list
    input_keys('ab')
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('b', @line_editor.line)
  end

  def test_em_delete_or_list_for_mbchar
    input_keys('かき')
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('き', @line_editor.line)
  end

  def test_em_delete_or_list_for_mbchar_by_plural_code_points
    input_keys("か\u3099き\u3099")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("き\u3099", @line_editor.line)
  end

  def test_ed_clear_screen
    refute(@line_editor.instance_variable_get(:@cleared))
    input_keys("\C-l")
    assert(@line_editor.instance_variable_get(:@cleared))
  end

  def test_ed_clear_screen_with_inputed
    input_keys("abc\C-b")
    refute(@line_editor.instance_variable_get(:@cleared))
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-l")
    assert(@line_editor.instance_variable_get(:@cleared))
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_em_next_word
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    input_keys("abc def{bbb}ccc\C-a\M-F")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-F")
    assert_equal(7, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-F")
    assert_equal(11, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(11, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-F")
    assert_equal(15, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-F")
    assert_equal(15, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor))
  end

  def test_em_next_word_for_mbchar
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    input_keys("あいう かきく{さしす}たちつ\C-a\M-F")
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(13, @line_editor.instance_variable_get(:@cursor))
    assert_equal(19, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(20, @line_editor.instance_variable_get(:@cursor))
    assert_equal(29, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
  end

  def test_em_next_word_for_mbchar_by_plural_code_points
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    input_keys("あいう か\u3099き\u3099く\u3099{さしす}たちつ\C-a\M-F")
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(13, @line_editor.instance_variable_get(:@cursor))
    assert_equal(28, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(20, @line_editor.instance_variable_get(:@cursor))
    assert_equal(38, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(48, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-F")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(48, @line_editor.instance_variable_get(:@byte_pointer))
  end

  def test_em_prev_word
    input_keys("abc def{bbb}ccc")
    assert_equal(15, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-B")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(12, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-B")
    assert_equal(8, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-B")
    assert_equal(4, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
  end

  def test_em_prev_word_for_mbchar
    input_keys("あいう かきく{さしす}たちつ")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(21, @line_editor.instance_variable_get(:@cursor))
    assert_equal(30, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(14, @line_editor.instance_variable_get(:@cursor))
    assert_equal(20, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
  end

  def test_em_prev_word_for_mbchar_by_plural_code_points
    input_keys("あいう か\u3099き\u3099く\u3099{さしす}たちつ")
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(48, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(21, @line_editor.instance_variable_get(:@cursor))
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(14, @line_editor.instance_variable_get(:@cursor))
    assert_equal(29, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    input_keys("\M-B")
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
  end

  def test_em_delete_next_word
    input_keys("abc def{bbb}ccc\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(12, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal(' def{bbb}ccc', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('{bbb}ccc', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('}ccc', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_em_delete_next_word_for_mbchar
    input_keys("あいう かきく{さしす}たちつ\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal(' かきく{さしす}たちつ', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('{さしす}たちつ', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('}たちつ', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_em_delete_next_word_for_mbchar_by_plural_code_points
    input_keys("あいう か\u3099き\u3099く\u3099{さしす}たちつ\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal(" か\u3099き\u3099く\u3099{さしす}たちつ", @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('{さしす}たちつ', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('}たちつ', @line_editor.line)
    input_keys("\M-d")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_ed_delete_prev_word
    input_keys('abc def{bbb}ccc')
    assert_equal(15, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-\C-H")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(12, @line_editor.instance_variable_get(:@cursor))
    assert_equal(12, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abc def{bbb}', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(8, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor))
    assert_equal(8, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abc def{', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(4, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abc ', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_ed_delete_prev_word_for_mbchar
    input_keys('あいう かきく{さしす}たちつ')
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-\C-H")
    assert_equal(30, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('あいう かきく{さしす}', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(20, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('あいう かきく{', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('あいう ', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_ed_delete_prev_word_for_mbchar_by_plural_code_points
    input_keys("あいう か\u3099き\u3099く\u3099{さしす}たちつ")
    assert_equal(48, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor))
    assert_equal(27, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\M-\C-H")
    assert_equal(39, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor))
    assert_equal(21, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("あいう か\u3099き\u3099く\u3099{さしす}", @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(29, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor))
    assert_equal(14, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("あいう か\u3099き\u3099く\u3099{", @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(10, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor))
    assert_equal(7, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('あいう ', @line_editor.line)
    input_keys("\M-\C-H")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('', @line_editor.line)
  end

  def test_ed_transpose_chars
    input_keys("abc\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-t")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('abc', @line_editor.line)
    input_keys("\C-f\C-t")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('bac', @line_editor.line)
    input_keys("\C-t")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('bca', @line_editor.line)
    input_keys("\C-t")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('bac', @line_editor.line)
  end

  def test_ed_transpose_chars_for_mbchar
    input_keys("あかさ\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-t")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('あかさ', @line_editor.line)
    input_keys("\C-f\C-t")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('かあさ', @line_editor.line)
    input_keys("\C-t")
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('かさあ', @line_editor.line)
    input_keys("\C-t")
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('かあさ', @line_editor.line)
  end

  def test_ed_transpose_chars_for_mbchar_by_plural_code_points
    input_keys("あか\u3099さ\C-a")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-t")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("あか\u3099さ", @line_editor.line)
    input_keys("\C-f\C-t")
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("か\u3099あさ", @line_editor.line)
    input_keys("\C-t")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("か\u3099さあ", @line_editor.line)
    input_keys("\C-t")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal("か\u3099あさ", @line_editor.line)
  end

  def test_ed_digit
    input_keys('0123')
    assert_equal(4, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('0123', @line_editor.line)
  end

  def test_ed_next_and_prev_char
    input_keys('abc')
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(1, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(1, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(2, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_next_and_prev_char_for_mbchar
    input_keys('あいう')
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(9, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_ed_next_and_prev_char_for_mbchar_by_plural_code_points
    input_keys("か\u3099き\u3099く\u3099")
    assert_equal(18, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-b")
    assert_equal(0, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(0, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(6, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(2, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(12, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(4, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(18, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
    input_keys("\C-f")
    assert_equal(18, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor))
    assert_equal(6, @line_editor.instance_variable_get(:@cursor_max))
  end

  def test_em_capitol_case
    input_keys("abc def{bbb}ccc\C-a\M-c")
    assert_equal(3, @line_editor.instance_variable_get(:@byte_pointer))
    assert_equal(3, @line_editor.instance_variable_get(:@cursor))
    assert_equal(15, @line_editor.instance_variable_get(:@cursor_max))
    assert_equal('Abc def{bbb}ccc', @line_editor.line)
  end
end
